In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
import cv2
import numpy as np 
import random
import os
from PIL import Image
import torchvision

In [ ]:
tf.__version__


'2.3.0'

In [ ]:

import torch
import torch.nn as nn
import torch.nn.functional as F 


In [ ]:
class Torch_Model(nn.Module):
   
    def __init__(self):
        super(Torch_Model,self).__init__()
        self.conv1=nn.Conv2d(in_channels=1,out_channels=16,kernel_size=3,padding=1)
        self.conv2=nn.Conv2d(in_channels=16,out_channels=32,kernel_size=3,padding=1)
        self.pool1=nn.MaxPool2d(kernel_size=6, stride = 6)
        self.dropout1= nn.Dropout(0.25)
        self.conv3=nn.Conv2d(in_channels=32,out_channels=64,kernel_size=(5,9))
        self.pool2=nn.MaxPool2d(kernel_size=2, stride =2)
        self.conv4=nn.Conv2d(in_channels=64,out_channels=64,kernel_size=(2,4))
        self.dropout2= nn.Dropout(0.5)
        self.conv5=nn.Conv2d(in_channels=64,out_channels=128,kernel_size=1)
        self.conv6=nn.Conv2d(in_channels=128,out_channels=1,kernel_size=1)


    def forward(self,x):

        x=F.relu(self.conv1(x))
        x=F.relu(self.conv2(x))
        x=self.pool1(x)
        x=self.dropout1(x)
        x=F.relu(self.conv3(x))
        x=self.pool2(x)
        x=F.relu(self.conv4(x))
        x=self.dropout2(x)
        x=F.relu(self.conv5(x))

        x=torch.sigmoid(self.conv6(x))
    
        return x

print("torch model go")

torch model go


In [ ]:
Non_Pedes_path= '/content/gdrive/MyDrive/Dataset/NonPedestrians/'
Non_Pedes_batch = os.listdir(Non_Pedes_path)
Non_Pedes = []

#Processing the dataset
for index in range(0,6500):
  sample_np= Non_Pedes_batch[index]
  img_path_np = Non_Pedes_path+sample_np
  x=Image.open(img_path_np)
  x = x.resize((48,96),Image.ANTIALIAS)
  x=x.convert('L')
	#x=x.convert('1')
  Non_Pedes.append(x)
  print(index)

#splitting the non Pedes dataset for train and test
label_np = [0]*6500
Non_Pedes=zip(Non_Pedes,label_np)
Non_Pedes=list(Non_Pedes)
Non_Pedes_train=Non_Pedes[:6000]
Non_Pedes_train=list(Non_Pedes_train)
Non_Pedes_test = Non_Pedes[6000:6500]
#print(Non_Pedes_train[:3])



In [ ]:
# # IMPORTING IMAGES FROM PEDES DATASET
Pedes_path= '/content/gdrive/MyDrive/Dataset/48x96/'
Pedes_batch = os.listdir(Pedes_path)
Pedes = []

#PROCESSING THE DATASET
for index in range(0,10000):
	# i = random.randint(0,8000)
  sample_p= Pedes_batch[index]
  img_path_p = Pedes_path+sample_p
  y=Image.open(img_path_p)
  y=y.convert('L')
	# /y=y.convert('1')
  Pedes.append(y)
  print(index)
 
#SPLITTING THE DATA SET INTO TEST AND TRAIN
label_p = [1]*10000
Pedes=zip(Pedes,label_p)
Pedes=list(Pedes)	
print(len(Pedes))
Pedes_train= Pedes[:9000]
Pedes_test = Pedes[9000:10000]
print(len(Pedes_test))
print(len(Pedes_train))

In [ ]:
#MERGING PEDES AND NON PEDES DATASET
train=Non_Pedes_train + Pedes_train
random.shuffle(train)
print(len(train))

#SPLITTING INTO DATA AND LABEL-TRAIN
train_data = [a[0] for a in train]
train_label = [a[1] for a in train]
print(train_data[0].size)
print(train_data[0].mode)

#CONVERTING TO ARRAY
for img in range(0,len(train)):
	train_data[img]=np.array(train_data[img])
print(train_data[0].size,"QWERTYUIOP")
train_data=np.array(train_data)
train_data=train_data/255

train_data=train_data.reshape(-1,1,48,96).astype('float32')
print("ASDFGH",train_data[0].shape,train_data[0])
train_label=np.array(train_label).astype('float32')

15000
(48, 96)
L
4608 QWERTYUIOP
ASDFGH (1, 48, 96) [[[0.49803922 0.54509807 0.5294118  ... 0.5137255  0.6        0.7058824 ]
  [0.41568628 0.42352942 0.3882353  ... 0.49019608 0.4862745  0.5882353 ]
  [0.36078432 0.38039216 0.36078432 ... 0.4509804  0.47843137 0.56078434]
  ...
  [0.4392157  0.4392157  0.42745098 ... 0.4        0.38431373 0.2901961 ]
  [0.42352942 0.42352942 0.42352942 ... 0.42352942 0.38039216 0.27058825]
  [0.44705883 0.43529412 0.42352942 ... 0.5254902  0.4392157  0.29411766]]]


In [ ]:
#SPLITTING INTO DATA AND LABEL-TEST

test=Non_Pedes_test + Pedes_test
random.shuffle(test)
test_data = [a[0] for a in test]
test_label = [a[1] for a in test]
print(len(test_data), len(test_label))
print(len(Pedes_test))
print(len(Pedes_train))
print(len(Non_Pedes_train))
print(len(Non_Pedes_test))

#CONVERTING TO ARRAY
for img in range(0,len(test)):
	test_data[img]=np.array(test_data[img])
test_data=np.array(test_data)
test_data=test_data/255
test_data=test_data.reshape(-1,1,48,96).astype('float32')
test_label=np.array(test_label)
test_label=test_label.astype('float32') # int to float for labels

1500 1500
1000
9000
6000
500


In [ ]:
"""
#EXTRA TEST FOR CONFIRMATION
test2 = [a[0] for a in Pedes_test]
test2_l=[a[1] for a in Pedes_test]
test2[0]=np.array(test2[0])
test2=np.array(test2)
test2=test2/255

test2=test2.reshape(1,48,96,1).astype('float32')
test2_l=np.array(test2_l)
"""

In [ ]:
import torch.utils.data
import torch.optim as optim 

In [ ]:
# DECLARING VARIABLES
epochs = 5
batch_size= 64
printfreq = 50


In [ ]:
# LOADING THE MODEL
Model=Torch_Model()

In [ ]:
#LOSS FUNCTION
lossfunc=torch.nn.BCELoss(reduction='mean')

In [ ]:
#OPTIMIZER
optimizer=optim.Adam(Model.parameters())

In [ ]:
# CREATING A TEXT FILE
log=open("train_write.txt","w")

#ANALYSIS
log.write("Batch Size : %d\n\n"%(batch_size))
log.write(str(Model)+'\n\n')
log.write("Optimizer : ADAM\n\n")
log.write("Epochs : %d\n\n"%(epochs))

12

In [ ]:
def custom_loader(data,label,batch):
    dataset=[]
    for i in range(len(data)):
        dataset.append([data[i],label[i]])
    loader=torch.utils.data.DataLoader(dataset,batch_size=batch,shuffle=True)
    return loader


train_loader=custom_loader(train_data,train_label,batch_size)
test_loader=custom_loader(test_data,test_label,batch_size)
print("good to go loader")

NameError: ignored

In [ ]:
# TRAINING ON THE DATASET
log=open("train_write.txt","w")
for e in range(0,epochs):
    
    train_loss=0.0
    running_loss=0.0
    valid_loss=0.0

    for i,data in enumerate(train_loader):
        x,y = data   
        optimizer.zero_grad() # zeroes the gradient buffers of all parameters

        output = Model(x)
        output = output.view(-1) #reshaping the tensor while being unsure of no of rows
        
        loss = lossfunc(output,y)
        running_loss+=loss.item()
        train_loss+=loss.item() # TENSOR TO SCALAR

        loss.backward()
        optimizer.step()

        if (i+1)%printfreq==0:
            log.write("Epoch: %d\tBatch: %d\nRunning Loss: %.4f\n"%(e+1,i+1,running_loss/printfreq))
            print("Epoch: ", e+1)
            print('Batch: ', i+1)
            print("Running Loss: ", running_loss/printfreq)
            running_loss=0.0
    
    log.write("\nEpoch %d Train Loss: %.4f\n"%((e+1),train_loss/len(train_loader)))
    print("Epoch: ", e+1)
    print("Train Loss: ", train_loss/len(train_loader))
    print("-----")
    
    log.write("Training Complete.")
    print('Training Complete')

Epoch:  1
Batch:  50
Running Loss:  0.500315748155117
Epoch:  1
Batch:  100
Running Loss:  0.26392386615276336
Epoch:  1
Batch:  150
Running Loss:  0.12625366054475307
Epoch:  1
Batch:  200
Running Loss:  0.0797039831802249
Epoch:  1
Train Loss:  0.21483789394074615
-----
Training Complete
Epoch:  2
Batch:  50
Running Loss:  0.050416648415848614
Epoch:  2
Batch:  100
Running Loss:  0.03408639492932707
Epoch:  2
Batch:  150
Running Loss:  0.028342556040734053
Epoch:  2
Batch:  200
Running Loss:  0.026181941418908537
Epoch:  2
Train Loss:  0.03459228237575673
-----
Training Complete
Epoch:  3
Batch:  50
Running Loss:  0.017071799389086664
Epoch:  3
Batch:  100
Running Loss:  0.027762780911289156
Epoch:  3
Batch:  150
Running Loss:  0.009992089393199422
Epoch:  3
Batch:  200
Running Loss:  0.0206999975501094
Epoch:  3
Train Loss:  0.017734723789010573
-----
Training Complete
Epoch:  4
Batch:  50
Running Loss:  0.004413403897488024
Epoch:  4
Batch:  100
Running Loss:  0.01415923510910943
E

In [ ]:
# Training Accuracy

Accuracy=0.0
ipsize=0

for data in train_loader:
    x,y=data
    
    output=Model(x)
    output = output.view(-1)
    
    #print(output.shape,y.shape,"ASDFGH")
    output=output.round() # ROUNDING OFF THE PROBABILITIES TO EITHER 0(<0.5) OR 1(>0.5)
    #print(output,"zxcvbnm")
    comp=torch.eq(output,y).type(torch.FloatTensor)
    Accuracy+=comp.sum().item()
    ipsize+=len(y)
    print(Accuracy,"Accuracyyyyy")
    # print("qwertyuiopqwertyuiop")
log.write("Training Accuracy: %.4f\n"%(Accuracy/ipsize*100))
print('Training Accuracy:' , Accuracy/ipsize*100)


32.0 Accuracyyyyy
64.0 Accuracyyyyy
96.0 Accuracyyyyy
128.0 Accuracyyyyy
160.0 Accuracyyyyy
192.0 Accuracyyyyy
223.0 Accuracyyyyy
255.0 Accuracyyyyy
287.0 Accuracyyyyy
319.0 Accuracyyyyy
351.0 Accuracyyyyy
383.0 Accuracyyyyy
415.0 Accuracyyyyy
447.0 Accuracyyyyy
479.0 Accuracyyyyy
511.0 Accuracyyyyy
543.0 Accuracyyyyy
575.0 Accuracyyyyy
607.0 Accuracyyyyy
639.0 Accuracyyyyy
671.0 Accuracyyyyy
703.0 Accuracyyyyy
735.0 Accuracyyyyy
767.0 Accuracyyyyy
799.0 Accuracyyyyy
831.0 Accuracyyyyy
863.0 Accuracyyyyy
895.0 Accuracyyyyy
927.0 Accuracyyyyy
959.0 Accuracyyyyy
991.0 Accuracyyyyy
1023.0 Accuracyyyyy
1055.0 Accuracyyyyy
1087.0 Accuracyyyyy
1119.0 Accuracyyyyy
1151.0 Accuracyyyyy
1183.0 Accuracyyyyy
1215.0 Accuracyyyyy
1247.0 Accuracyyyyy
1279.0 Accuracyyyyy
1311.0 Accuracyyyyy
1343.0 Accuracyyyyy
1375.0 Accuracyyyyy
1407.0 Accuracyyyyy
1439.0 Accuracyyyyy
1471.0 Accuracyyyyy
1503.0 Accuracyyyyy
1534.0 Accuracyyyyy
1566.0 Accuracyyyyy
1598.0 Accuracyyyyy
1630.0 Accuracyyyyy
1662.0 Accurac

In [ ]:
# Testing Accuracy

Accuracy=0.0
ipsize=0

for data in test_loader:
    x,y=data
    output=Model(x)
    output = output.view(-1)
    
    output=output.round()
    comp=torch.eq(output,y).type(torch.FloatTensor)
    Accuracy+=comp.sum().item()
    ipsize+=len(y)
    print("after2")
log.write("Testing Accuracy: %.4f\n"%(Accuracy/ipsize*100))
print('Testinf Accuracy: ', Accuracy/ipsize*100)

In [ ]:
#SAVING THE MODEL 
torch.save(Model,'model.pt')

In [ ]:
from matplotlib import cm
from PIL import Image,ImageDraw

In [ ]:
working_model=torch.load('model.pt')
working_model.eval()

Torch_Model(
  (conv1): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool1): MaxPool2d(kernel_size=6, stride=6, padding=0, dilation=1, ceil_mode=False)
  (dropout1): Dropout(p=0.25, inplace=False)
  (conv3): Conv2d(32, 64, kernel_size=(5, 9), stride=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv4): Conv2d(64, 64, kernel_size=(2, 4), stride=(1, 1))
  (dropout2): Dropout(p=0.5, inplace=False)
  (conv5): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1))
  (conv6): Conv2d(128, 1, kernel_size=(1, 1), stride=(1, 1))
)

In [ ]:
def generate_test_img():
	img = Image.open('test4.jpg')
	img=img.convert('L')
	print(img.size)
	# img.save('rgb.jpg')
	if img.size[0]>2000 and img.size[1]>1000:
		img=img.resize((1000,2000),Image.ANTIALIAS)
	else:
		img=img.resize((img.size[0],img.size[1]),Image.ANTIALIAS)
	print(img.mode)
	return img

In [ ]:
def generate_test_img_array(img):
	h=img.size[0]
	w=img.size[1]
	img=np.array(img)
	img=img/255
	img=img.reshape(1,1,h,w).astype('float32')
	print(img.shape)
	return img

In [ ]:
test1=generate_test_img()
test1_arr=generate_test_img_array(test1)


(1140, 760)
L
(1, 1, 1140, 760)


In [ ]:
#@title Sliding window form
x_val =  2#@param {type:"number"}
y_val =  3.2#@param {type:"number"}
thresh =  0.98#@param {type:"number"}


In [ ]:
def sw(image,image_array, x =x_val, y=y_val, save_files = True, threshold = thresh):


	#CONVERTING NUMPY ARRAY TO TENSOR AND PUTTING IT IN MODEL
  image_tensor = torchvision.transforms.functional.to_tensor(image)
  image_tensor = torch.unsqueeze(image_tensor,0)
  output_tensor = working_model(image_tensor)
  print("out",output_tensor.shape)
  output_squeeze = torch.squeeze(output_tensor,0).detach().numpy() # all dimensions of size 1 removed
  print(output_squeeze.shape)

  heatmap = output_squeeze[0] # the channel or the 2nd one is eliminated
  print(heatmap,"HEATMAP",heatmap.shape)
  heatmap_thr = heatmap.copy()

	# applying threshold or a simpler version of non-max suppression
  heatmap_thr[heatmap[:,:]>threshold] = 100
  heatmap_thr[heatmap[:,:]<=threshold] = 0

  boxes=[]

	#converting PIL image to DrawImage
  image_copy = image.copy()
  draw = ImageDraw.Draw(image)
  draw_copy = ImageDraw.Draw(image_copy)

  heatmap_img = Image.fromarray(np.uint8(cm.gist_earth(heatmap)*255))
  heatmap_img.show()

  print("with threshold")
  heatmap_img_thresh = Image.fromarray(np.uint8(cm.gist_earth(heatmap_thr)*255))
  heatmap_img_thresh.show()
	# print(heatmap.shape[0])
  print("---------")
	# print(np.arange(heatmap.shape[0]))
  print("----------")
	
	# yy-rows have the same elements, xx- columns have the same elements
  xx,yy = np.meshgrid(np.arange(heatmap.shape[1]),np.arange(heatmap.shape[0])) 
	
	# x_det and y_det contain all those indices of heatmap whose value is greater than threshold.
  x_det = (xx[heatmap[:,:]>threshold]) 
  y_det = (yy[heatmap[:,:]>threshold])
  print(y_det)

	# Scaling of the model
  shrink_ratio = (image.width/heatmap_img.width , image.height/heatmap_img.height)
  print('Shrink Ratio: ', shrink_ratio)
	
	# Appending the dimensions of the bounding boxes
  for i,j in zip(x_det,y_det): 
		  boxes.append([int(i*9),int(j*9),int(i*9 + 48 + 400),int(j*9 + 96 + 400)])

	#group interecting rectanlgles
  bound_boxes = cv2.groupRectangles(boxes,2,1)
  bound_boxes=bound_boxes[:1]

  print("Number of Objects: ",len(bound_boxes[0]))
  print(bound_boxes)

	# draw the box on the image and its copy
  for box in bound_boxes:
	  for b in box:
		  print(b,"BOX")
		  draw_copy.rectangle((b[0],b[1],b[2]+b[0],b[1]+b[3]),outline='blue') #draw.draw_rectangle(xy, ink, 0, width)

  for box in bound_boxes[0]:
	  draw.rectangle((box[0]-(x-1)*box[2]//2,box[1]-(y-1)*box[2]//2,box[2]*x+box[0]-(x-1)*box[2]//2,box[3]*y+box[1]-(y-1)*box[2]//2),outline='green')

	#saving the images
  if(save_files) :
	  image.save("Actual output.png")
	  image_copy.save("Copy_Output.png")
	  heatmap_img.save("Heatmap.png")
	  heatmap_img_thresh.save("Heatmap_thresh.png")
	
  image.show()

In [ ]:
sw(test1,test1_arr)

out torch.Size([1, 1, 60, 88])
(1, 60, 88)
[[0.9791895  0.9971355  0.9945687  ... 0.99285066 0.9945785  0.9961313 ]
 [0.88734996 0.9914726  0.9762332  ... 0.986299   0.9884035  0.9682975 ]
 [0.8539009  0.99236053 0.9683253  ... 0.98708355 0.99136496 0.9886236 ]
 ...
 [0.96584207 0.9988463  0.9731915  ... 0.81376326 0.00452625 0.00324069]
 [0.00235549 0.9267191  0.21642934 ... 0.9909958  0.99764025 0.9964258 ]
 [0.60249764 0.97096956 0.23830423 ... 0.94289124 0.966161   0.9324687 ]] HEATMAP (60, 88)
with threshold
---------
----------
[ 0  0  0 ... 59 59 59]
Shrink Ratio:  (12.954545454545455, 12.666666666666666)
Number of Objects:  1
(array([[482, 222, 930, 718]], dtype=int32),)
[482 222 930 718] BOX
